### ISSUE TITLE
Symfony CMF doesn't support sonata-project/doctrine-phpcr-admin-bundle

### ISSUE THREAD

**Issue by MaxArt2501** [symfony-cmf/standard-edition#61]
Not out of the box, at least.

As soon as I installed v1.3 as specified in [the official docs](http://symfony.com/doc/1.3/cmf/book/installation.html) (with `compose create-project`, that is), I tried to install Sonata's PHPCR admin bundle with just `composer require sonata-project/doctrine-phpcr-admin-bundle`. But the requested packages conflicted with the ones installed by the created project.

The problematic package was [`sonata-project/block-bundle`](https://packagist.org/packages/sonata-project/block-bundle), which was locked to 2.3.9. But [`sonata-project/admin-bundle`](https://packagist.org/packages/sonata-project/admin-bundle) 3.x, which is required by `doctrine-phpcr-admin-bundle`, requires it to be ^3.0.

What I had to do was:

* regrade `sensio/generator-bundle` to version ~2.5 (as it was necessary for the `admin-bundle` I had to use);
* require the very specific `sonata-project/admin-bundle:2.3.1` (because from 2.3.2 it limited `sonata-project/block-bundle` to the very tiny range ~2.2,>=2.2.7,<2.3);
* finally require [`sonata-project/doctrine-phpcr-admin-bundle`](https://packagist.org/packages/sonata-project/doctrine-phpcr-admin-bundle).

This is clearly sub-optimal and tiresome for developers who just want to start already. I don't even know if I could have made a better choice (any suggestions?). In particular I'm worried about regrading `generator-bundle` and providing a version of `sonata-project/block-bundle` that has been excluded by `admin-bundle` a bugfix-version later.

I understand the development of this package is focused on v2.0, but is there a chance to overcome this issue?
Could `symfony-cmf/block-bundle:1.3` be compatible with `sonata-project/block-bundle:3.x`? That would solve basically everything, if I'm not mistaken.

**Comment by wouterj** [comment]
Hi @MaxArt2501!

You can have a look at the [`composer.json` of the CMF sandbox](https://github.com/symfony-cmf/cmf-sandbox/blob/bb07f3f2db60441f779fdbbf14932de071e09336/composer.json) during the 1.3.0 release. This is a fully working set of dependencies using CMF 1.3 and Sonata packages.

Sonata before 3.0 has always been very hard to integrate in the project, because they add backwards compatibility breaks in almost every release. This is the reason you get these small version constraints. I'm not sure we can do anything about it. IIRC, this is also the reason we can't support BlockBundle 3.0 in a CMfBlockBundle 1.3 release (they changed argument typehints of methods we have to overwrite).

Btw, you don't have to be worried about the generator-bundle regrading. This bundle is only used when you use the generator commands. So it wouldn't hurt your application at all.

**Comment by MaxArt2501** [comment]
Thank you for the quick response!
Good suggestion about the sandbox, it seems it *is* possible to use a more recent, up-to-date `admin-bundle`. So, as an alternative, I could have required an older version of `sonata-project/block-bundle` (like 2.2.x) and get `admin-bundle:2.3.10`.

I look forward for CMF v2.0 when all this will be solved.

**Comment by wouterj** [comment]
> I look forward for CMF v2.0 when all this will be solved.

Please note that in CMF 2.0, Sonata stuff will all be moved to a new SonataIntegration bundle. I'm not sure if we can make a release of that bundle at the same time as the 2.0 release of other CMF bundles (as we're hold up by Sonata on that bundle, while we really want to have stable versions that support Sf 3.0).

I assume this issue is now solved and it can be closed?

**Comment by MaxArt2501** [comment]
Well it doesn't actually solve the issue but if there's nothing that can be done I guess this can be closed.
This can be as good as a guide for newcomers.
